version: "3.8"

services:
  menulog-web:
    container_name: menulog-web
    build:
      context: web
    volumes:
      - ..:/var/www/app:delegated
      - /root/.composer/cache
      - /root/.npm
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - menulog-db

  menulog-db:
    container_name: menulog-db
    image: mysql:8.0.29
    platform: linux/x86_64
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:3306

  dbadmin:
    container_name: menulog-dbadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=menulog-db
      - PMA_USER=root
      - PMA_PASSWORD=password
    volumes:
      - /sessions
    ports:
      - ${MYADMIN_PORT}:80
    depends_on:
      - menulog-db
